// "use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Script from "next/script";
import SessionProvider from '@/app/components/providers/sessionProvider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pubshine  - Premium AdTech Monetization",
  keywords: "Pubshine, AdTech, Monetization, Publishers, Revenue Optimization, VideoWall, Header Bidding, Google AdX",
  authors: [{ name: "Stephany Emmitty", url: "https://pubshine.com" }],
  creator: "Stephany Emmitty",
  openGraph: {
    title: "Pubshine - Premium AdTech Monetization",
    description: "Maximize your ad revenue with Pubshine's advanced AdTech solutions. Join top publishers earning $500K+ monthly.",
    url: "https://pubshine.com",
    siteName: "Pubshine",
    images: [
      {
        url: "/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "Pubshine - Premium AdTech Monetization",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Pubshine - Premium AdTech Monetization",
    description: "Maximize your ad revenue with Pubshine's advanced AdTech solutions. Join top publishers earning $500K+ monthly.",
    images: ["/images/favicon.png"],
  },
  icons: {
    icon: "/images/favicon.ico",
    apple: "/images/favicon.ico",
  },
  themeColor: "#000000",
  robots: {
    index: true,
    follow: true,
  },
  viewport: "width=device-width, initial-scale=1",
  appleWebApp: {
    capable: true,
    title: "Pubshine",
    statusBarStyle: "black-translucent",
  },
  manifest: "/manifest.json",
  creator: "Stephany Emmitty",
  publisher: "Pubshine",
  robots: "index, follow",
  themeColor: "#000000",
  applicationName: "Pubshine",
  referrer: "no-referrer-when-downgrade",
  keywords: "AdTech, Monetization, Publishers, Revenue Optimization, VideoWall, Header Bidding, Google AdX",
  authors: [{ name: "Stephany Emmitty", url: "https://pubshine.com" }],
  creator: "Stephany Emmitty",
  publisher: "Pubshine",
  robots: "index, follow",
  themeColor: "#000000",
  applicationName: "Pubshine",
  referrer: "no-referrer-when-downgrade",
  generator: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <title>PubShine – Maximize Your Ad Revenue</title>
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="./globals.css" />
        {/* <Script
          src="https://embed.tawk.to/6975bf6c9602761980a88658/1jfpv7gpc"
          strategy="afterInteractive"
        /> */}
        
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full !bg-black max-w-full !overflow-x-hidden`}
      >
        <SessionProvider>
        <Toaster />
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
